version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: userpasswd
  drupal:
    image: drupal
    volumes:
      - ./drupal-src:/tmp
    ports:
      - '80:80'
    depends_on:
      - mysql