version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: userpasswd
    volumes:
      - ./db/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
  drupal:
    container_name: drupal
    image: local-drupal:v1
    volumes:
      - ./drupal-src:/opt/drupal
    ports:
      - '80:80'
    depends_on:
      - mysql