# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testdrupal0307

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrhs0306.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1e37ede82dbb43a39caeaa401e8ebcf7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b60bd146527749a3b8f0983044a1d617 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrhs0306.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1e37ede82dbb43a39caeaa401e8ebcf7 }}/custom-drupal:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdrupal0307'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c5ca0704aa343c6b7634f9f29f14217 }}
        images: 'acrhs0306.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1e37ede82dbb43a39caeaa401e8ebcf7 }}/custom-drupal:${{ github.sha }}'